AddMakanan/urls.py
from django.urls import path
from . import views

app_name = 'addMakanan'

urlpatterns = [
    path('', views.addMakanan, name='addMakanan'),
    path('success', views.success, name='success'),
]

Feedback/urls.py
from django.urls import path
from . import views

app_name = 'Feedback'

urlpatterns = [
    path('', views.feedback, name='Feedback'),
    path('viewfeedback', views.viewfeedback, name='viewfeedback'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
]

kantinin/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('pilihkantin/',include('pilihKantin.urls')),
    path('addmakanan/',include('AddMakanan.urls')),
    path('feedback/',include('Feedback.urls')),

]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
            settings.MEDIA_ROOT,}),
    ]

pilihKantin/urls.py
from django.urls import path
from . import views

app_name = 'pilihKantin'

urlpatterns = [
    path('', views.pilihKantin, name='pilihKantin'),
    path('home', views.home, name='home'),
]

AddMakanan/models.py
import os
from django.db import models

# Create your models here.
Kantin = (
    ('counter1','Counter1'),
    ('counter2','Counter2'),
    ('counter3','Counter3'),
    ('counter4','Counter4'),
    ('counter5','Counter5'),
    ('counter6','Counter6'),
    ('counter7','Counter7'),
    ('counter8','Counter8'),
    ('counter9','Counter9'),
    ('counter10','Counter10'),
    ('counter11','Counter11'),
    ('counter12','Counter12'),
    ('counter13','Counter13'),
    ('counter14','Counter14'),
    ('counter15','Counter15'),
    ('counter16','Counter16'),
    ('counter17','Counter17'),
    ('counter18','Counter18'),
    ('counter19','Counter19'),
    ('counter20','Counter20'),
    ('counter21','Counter21'),
    ('counter22','Counter22'),
)

Jenis_Makanan = (
    ('snack','Snack'),
    ('maincourse','Main Course'),
    ('dessert','Dessert'),
    ('beverages','Beverages'),
)

class Makanan(models.Model):
    kantin = models.CharField(max_length = 20, choices = Kantin)
    nama = models.CharField(max_length = 50)
    harga = models.IntegerField(default = 0)
    jenisMakanan = models.CharField(max_length = 20, choices = Jenis_Makanan)
    gambarMakanan = models.ImageField(blank = True, null = True, upload_to = "makananImage/%Y/%m/%D/", default ="icon.png")

Feedback/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    nama = models.CharField(max_length = 30)
    pesan = models.CharField(max_length = 500)

homepage/models.py
from django.db import models

# Create your models here.

pilihKantin/models.py
from django.db import models

# Create your models here.

AddMakanan/forms.py
from django import forms
from .models import Makanan

class MakananForm(forms.ModelForm):
    class Meta:
        model = Makanan
        fields = ('kantin','nama','harga','jenisMakanan', 'gambarMakanan')
        labels = {
            'kantin'        : "Kantin              :",
            'nama'          : "Nama Makanan        :",
            'harga'         : "Harga               :",
            'jenisMakanan'  : "Jenis Makanan       :",
            'gambarMakanan' : "Foto Makanan        :",
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

Feedback/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['nama', 'pesan']
        labels = {'nama' : 'Nama', 'pesan' : 'Pesan'}
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text'}),
            'pesan' : forms.Textarea(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'size':100})
        }

AddMakanan/views.py
from django.shortcuts import render, redirect
from .models import Makanan
from .forms import MakananForm

# Create your views here.

def addMakanan(request):
    if request.method == 'POST':
        form = MakananForm(request.POST, request.FILES)
        if form.is_valid(): 
            form.save()
            return redirect('addMakanan:success')
    else:
        form = MakananForm()
    return render(request, 'addMakanan.html', {'form' : form})

def success(request):
    makanan = Makanan.objects.all()
    return render(request, 'success.html', {'form' : makanan})

Feedback/views.py
from django.shortcuts import render, redirect
from .models import Feedback
from .forms import FeedbackForm

# Create your views here.
def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            # return redirect('Feedback:feedback')
    else:
        form = FeedbackForm()
    return render(request, 'feedback.html', {'form' : form})

def viewfeedback(request):
    data = Feedback.objects.all()
    return render(request, 'view-feedback.html', {'form' : data})

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

pilihKantin/views.py
from django.shortcuts import render
from AddMakanan.models import Makanan

# Create your views here.

def is_valid_queryparam(param):
    return param != '' and param is not None

def pilihKantin(request):
    makanan = Makanan.objects.all()
    title_contains_query=request.GET.get('title_contains')
    if is_valid_queryparam(title_contains_query):
        makanan = makanan.filter(nama__icontains=title_contains_query)

    return render(request, 'pilihKantinHome.html', {'form' : makanan})

def home(request):
    return render(request, 'pilihKantin.html')

AddMakanan/templates/addMakanan.html
<!DOCTYPE html>
<html lang="en">
  {% load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kantinin.id | Add Makanan</title>
    <!-- Website Logo -->
    <link rel="icon" type="image/png" href="{% static 'icon.png' %}">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light"style="background-color: #FFFFFF;">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">
            <img src="{% static 'text.png' %}" alt=""style="width:129px;height: 39px">
        </a>
    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pilihKantin:home' %}">Pilih Kantin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:home' %}">Recomended</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:home' %}">Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Feedback:Feedback' %}">Feedback</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'addMakanan:addMakanan' %}">Add Makanan</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="col-sm-12" style="height: 10%;background-color: white">
        <img src="{% static 'Logo.png' %}" style="  display: block;margin-left: auto;margin-right: auto;width: 50%;">
    </div>

    <!-- Content -->
    <div class="section2"style="height: 45%;">
      
      <div class="content">
        <div class="row">
          <div class="col-md-6">
            <br><br>
              <div class="header">
                  <h1 class="card-title text-center" style="color:darkslategrey; text-align: center;">Add Makanan</h1>
                </div>
          </div>
          <div class="col-md-6" style="color:darkslategrey;">
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                  <div class="form-group">
                    {{ form }}
                  </div>
                </table>
                <br>
                <button type="submit" class="btn btn-success">
                  Add Makanan
                </button>
              </form>
          </div>
        </div>
          
      </div>
      
    </div>

    </div>
    </div>
    </div>
<!-- Footer -->
<footer style="background-color: black; color: white;" class="page-footer">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: Kantinin.id</div>
</footer>    

</body>
</html>

AddMakanan/templates/success.html
<!DOCTYPE html>
<html lang="en">
  {% load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kantinin.id | Add Makanan</title>
    <!-- Website Logo -->
    <link rel="icon" type="image/png" href="{% static 'icon.png' %}">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light"style="background-color: #FFFFFF;">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">
            <img src="{% static 'text.png' %}" alt=""style="width:129px;height: 39px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pilihKantin:home' %}">Pilih Kantin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:home' %}">Recomended</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:home' %}">Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Feedback:Feedback' %}">Feedback</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'addMakanan:addMakanan' %}">Add Makanan</a>
                </li>
            </ul>
    </div>
    </nav>
    <div class="container mt-5">
        <h5 class="text-success text-center">Berhasil menambahkan makanan <a href="{% url 'addMakanan:addMakanan' %}">klik disini</a> untuk kembali...</h5>
    </div>

    <div class="col-sm-12" style="height: 10%;background-color: white">
        <img src="{% static 'Logo.png' %}" style="  display: block;margin-left: auto;margin-right: auto;width: 50%;">
    </div> 

<!-- Footer -->
<footer style="background-color: black; color: white;" class="page-footer">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: Kantinin.id</div>
</footer>

</body>
</html>

Feedback/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
    {% load static%}
<head>
    <title>Feedback</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color: #59554E;">
    <nav class="navbar navbar-expand-lg navbar-light"style="background-color: #FFFFFF;">
            <a class="navbar-brand" href="{% url 'homepage:home' %}">
                <img src="{% static 'text.png' %}" alt=""style="width:129px;height: 39px">
            </a>
        
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pilihKantin:home' %}">Pilih Kantin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Recomended</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Feedback:Feedback' %}">Feedback</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'addMakanan:addMakanan' %}">Add Makanan</a>
                    </li>
                </ul>
            </div>
        </nav>

    <!-- Feedback -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9" style="margin-bottom: 2vw; padding-right: 3vw;">
                <div style="margin-bottom: 4vw; margin-top: 4vw">
                    <h1 style="color:white">Feedback</h1>
                    <h4 style="color:white">Let us know your feedback</h4>
                </div>
                <div>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group"> 
                            <label for="nama" style="color:white">Nama</label>
                            {{form.nama}}
                        </div>
                            <div class="form-group"> 
                            <label for="pesan" style="color:white">Pesan</label>
                            {{form.pesan}}
                        </div>
                        <button type="submit" class="btn btn-light" value="Save">Send</button>
                    </form>
                </div>
            </div>
            <div class="col-md-3 text-center" style="background-color: #A1C1BE">
                <h3 style="color:darkslategrey; margin-top: 15vw; text-align: center;">Read some feedbacks from our visitors</h3>
                <a style="margin-top:3vw; margin-bottom: 10vw;" class="btn btn-dark" href="{% url 'Feedback:viewfeedback' %}">click here</a>
            </div>
        </div>
    </div>


<!-- Footer -->
<footer style="background-color: black; color: white;" class="page-footer">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: Kantinin.id</div>
</footer>
    
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

Feedback/templates/view-feedback.html
<!DOCTYPE html>
<html lang="en">
    {% load static%}
<head>
    <title>Feedback</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light"style="background-color: #FFFFFF;">
            <a class="navbar-brand" href="{% url 'homepage:home' %}">
                <img src="{% static 'text.png' %}" alt=""style="width:129px;height: 39px">
            </a>
        
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pilihKantin:home' %}">Pilih Kantin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Recomended</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Feedback:Feedback' %}">Feedback</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'addMakanan:addMakanan' %}">Add Makanan</a>
                    </li>
                </ul>
            </div>
        </nav>

    <!-- Tampilan feedback -->
    <div class="container-fluid">
        <div style="margin-bottom: 4vw; margin-top: 4vw">
            <h3>Feedbacks from our visitors</h3>
        </div>
        <div>
            {% for item in form %}
            <div class="col-sm-3"style="">
                <div class="card" style="width: 50rem;margin-top:5%;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Nama : {{ item.nama }}</li>
                        <li class="list-group-item">Pesan : {{ item.pesan }}</li>
                    </ul>                  
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

<!-- Footer -->
<footer style="background-color: black; color: white; margin-top: 13vw;" class="page-footer">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: Kantinin.id</div>
</footer>
    
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

pilihKantin/templates/pilihKantin.html
<!DOCTYPE html>
<html lang="en">
    <!DOCTYPE html>
    <html lang="en">
      {% load static%}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Kanintin.id | Pilih Kantin</title>
        <!-- Website Logo -->
        <link rel="icon" type="image/png" href="{% static 'icon.png' %}">
         <!-- CSS -->
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light"style="background-color: #FFFFFF;">
            <a class="navbar-brand" href="{% url 'homepage:home' %}">
                <img src="{% static 'text.png' %}" alt=""style="width:129px;height: 39px">
            </a>
        
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pilihKantin:home' %}">Pilih Kantin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Recomended</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Feedback:Feedback' %}">Feedback</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'addMakanan:addMakanan' %}">Add Makanan</a>
                    </li>
                </ul>
            </div>
        </nav>
      <div class="row">
    <div class="col-sm-12" style="height:57em ;background-color: #E2E3D9">
        <img src="" style="  display: block;margin-left: auto;margin-right: auto;width: 50%;">
        <h2 style="margin: 2.75%;">Pilihan Kantin</h2>
        <div id="pilihKantin">
            <ul id = "kantinul">
            <li>
            <a class="kantinp" href="{% url 'pilihKantin:pilihKantin' %}">Kantin Fasilkom</a>
            <img style="width: 50%; padding: 4%;"src="https://scontent.fcgk4-4.fna.fbcdn.net/v/t1.0-9/39714740_946681102185735_2481526726606192640_o.jpg?_nc_cat=105&_nc_oc=AQndFnuARS4QKL-yoUKdmgO9nBywqVVYkr6ZDhVj5zYWm3KZvVzXXBteubx8_tPiKLE&_nc_ht=scontent.fcgk4-4.fna&oh=977083e206386f7d33d7fe786646ccfd&oe=5E1B7CFD"> 
            <li>
        </ul>
        </div>
    </div>

    <!-- Footer -->
<footer class="container-fluid" style="background-color: black; color: white;" class="page-footer">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: Kantinin.id</div>
</footer>

    </body>
    </html>